### ISSUE TITLE
Fix: populating feed does not work on Heroku, but does work locally.

### ISSUE THREAD

**Issue by uschtwill** [uschtwill/rails_rss_reader#1]
Relevant code:
https://github.com/uschtwill/rails_rss_reader/blob/master/app/views/layouts/_navigation.slim
https://github.com/uschtwill/rails_rss_reader/blob/master/config/routes.rb
https://github.com/uschtwill/rails_rss_reader/blob/master/app/controllers/blogs_controller.rb
https://github.com/uschtwill/rails_rss_reader/blob/master/app/models/blog.rb

I don't understand. @alvinkatojr, could you take a look?

**Comment by alvinkatojr** [comment]
My connection is down man. I will look into it when its back on.

**Comment by uschtwill** [comment]
Cool, standing by.

**Comment by ghost** [comment]
Will what are the variables the API is giving? Is it the url, title and description only?

**Comment by uschtwill** [comment]
@kevalsha Look here: #2 .

**Comment by alvinkatojr** [comment]
@uschtwill I am going to need a demo of this locally and then on heroku. Could be something was n't configured correctly during the push.

**Comment by uschtwill** [comment]
@alvinkatojr Sure thing!

**Comment by uschtwill** [comment]
@alvinkatojr  Nevermind. Seems to be working all of a sudden... o_O

**Comment by alvinkatojr** [comment]
ha ha @uschtwill sometimes you need a break from the computer for these things to work as expected :)

**Comment by uschtwill** [comment]
@alvinkatojr Apparently! :)
