### ISSUE TITLE
Todo: Add search and filter functionality

### ISSUE THREAD

**Issue by uschtwill** [uschtwill/rails_rss_reader#16]

**Comment by uschtwill** [comment]
Need to discuss this with @alvinkatojr ?

**Comment by dwanjuhi1** [comment]
maybe add tags for future iterarions?

**Comment by ghost** [comment]
And perhaps include tags for future iterations?

**Comment by uschtwill** [comment]
@alvinkatojr High Prio!

**Comment by alvinkatojr** [comment]
@uschtwill for the search you will need a controller and an action that does the searching. The key thing is what exactly are you searching for? Some hints of code that would be in the search action: User.find_by or Article.find_by and finally a full text search of everything. 

For the tags use a gem, 'acts like taggable' is a good one @dwanjuhi1.

**Comment by uschtwill** [comment]
Fixed with help from the great Alvin. When using forms relating to stuff that does not go into the database , one ought to use a `form_tag` helper, not a `form_for` helper.

Putting the idea with the tags in a separate issue for visibility and so this can be closed.
