### ISSUE TITLE
ToDo: figure out how to shorten blogposts on the index page

### ISSUE THREAD

**Issue by ghost** [uschtwill/rails_rss_reader#22]

**Comment by uschtwill** [comment]
@dwanjuhi1 Fixed the implementation, the call to the Trunkator apparently does go in the view. 

This still needs a 'Read more' link now. This could be a piece of cake, and I just wanted to do it quickly myself. But it might get a bit tricky. Somehow the routes are broken: /entries/:id currently spits the user out at the index view, which of course fails. On the other hand it seems like the route seems alright, as it maps to the show action of the controller. 

So this is really weird to me, no idea what to do about it...

Check out the screenshot:
![screen shot 2015-03-17 at 10 28 00](https://cloud.githubusercontent.com/assets/10156948/6682971/a938c664-cc90-11e4-8587-8c29a8ce6df8.png)

**Comment by uschtwill** [comment]
@alvinkatojr High Prio.

**Comment by alvinkatojr** [comment]
@dwanjuhi1 and @uschtwill I did this sometime back on a rails app. I wrote a method that trims the length of a blog post and then called that method on the index page. Check it out [here](https://github.com/alvinkatojr/noteful/commit/305cc021ab726a7aa063ce20c4ca4fa5dd193036). I called that method on the index view and it did the necessary. 

There are also some helper methods that are useful in doing this kind of thing. I'd advise you to check out the helpers in rails and see what magic you can perform or come up with.

**Comment by uschtwill** [comment]
@alvinkatojr dude, did you even read what we wrote? we had that implemented already, the error was regarding something else. :D
