### ISSUE TITLE
TO DO: Create Contribution Guideline

### ISSUE THREAD

**Issue by DavidLemayian** [uschtwill/rails_rss_reader#46]
A `CONTRIBUTION.md` file would be awesome.

**Comment by uschtwill** [comment]
@DavidLemayian First I would have to know what a contribution guideline usually includes. Maybe you can point me towards a couple of good ones? :)

**Comment by DavidLemayian** [comment]
I think the best would be off the Github help docs - https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by uschtwill** [comment]
Yeah, I already got a couple of good ones. Already working on it.

**Comment by uschtwill** [comment]
https://github.com/uschtwill/rails_rss_aggregator/blob/master/CONTRIBUTING.md

What do you think?

**Comment by uschtwill** [comment]
@dwanjuhi1 Anything to add?

**Comment by uschtwill** [comment]
I think this should do, let me know what you think. ^^

**Comment by DavidLemayian** [comment]
Excellent stuff @uschtwill !

**Comment by uschtwill** [comment]
:)
