### ISSUE TITLE
To-do: Take all the award-winning bloggers from the iHub bash and add them to the blogs-list

### ISSUE THREAD

**Issue by uschtwill** [uschtwill/rails_rss_reader#9]
#### To be found here:

http://community.ihub.co.ke/blogs/22826/the-100-tech-community-appreciation-awards
#### Also add:

iafrikan.com
techmoran
white african
possibly twitter feeds of above famous people
#### Resources for converting Twitter feeds to RSS feeds:

http://www.labnol.org/internet/twitter-rss-feed/28149/
https://twitrss.me/
http://www.thisisafricaonline.com/
http://thisisafrica.me/
http://africasacountry.com/

**Comment by uschtwill** [comment]
@alvinkatojr @tamzi @kevalsha 

Haha, alright guys, check out what it looks like now... https://salty-sierra-8863.herokuapp.com/

It now actually renders all the tags properly. There is some serious mayhem going on in regards to image sizes, but I think this could be something.

Read this issue (above).

Basically the idea would be to make this a Naitobi-tech-blog-and-news-aggregator that just aggregates the shit out of what is currently going on in the space. Could be cool... whatcha guys think?

**Comment by ghost** [comment]
http://whiteafrican.com/feed/ 
http://bankelele.co.ke/feed
http://feeds.feedburner.com/techweez
http://www.iafrikan.com/rss/ 

No RSS feeds:
http://techmoran.com/#sthash.gNubOHpI.dpbs 
http://www.kachwanya.com/
http://www.moseskemibaro.com/

**Comment by ghost** [comment]
Also, should we add Twitter feeds as well? People may tweet outside of tech and that would be included in our app, and that wouldn't be ideal.
